CREATE DATABASE IF NOT EXISTS `auth_db`
  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

USE `auth_db`;

SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `token`;

CREATE TABLE `token` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(512) NOT NULL,
  `type`  VARCHAR(20)  NOT NULL,          -- npr. 'BEARER'
  `revoked` TINYINT(1) NOT NULL DEFAULT 0,
  `expired` TINYINT(1) NOT NULL DEFAULT 0,
  `user` VARCHAR(255) NOT NULL,           -- FK na auth_db.user(username)
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_token_token` (`token`),
  CONSTRAINT `fk_token_user`
    FOREIGN KEY (`user`) REFERENCES `user`(`username`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET SQL_MODE=@OLD_SQL_MODE;
