server:
  port: 8084

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/users/**
        - id: class-service
          uri: http://class-service:8083
          filters:
            - AddRequestHeader=X-Gateway-Auth,valid
          predicates:
            - Path=/classes/**
        - id: auth-service
          uri: http://auth:8081
          predicates:
            - Path=/auth/**
        - id: attendance-service
          uri: http://attendance:8085
          filters:
            - AddRequestHeader=X-Gateway-Auth,valid
          predicates:
            - Path=/absences/**, /lessons/**
        - id: grade-service
          uri: http://grade-service:8086
          filters:
            - AddRequestHeader=X-Gateway-Auth,valid
          predicates:
            - Path=/grades/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true