server:
  port: 8084

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**,/teachers/**,/students/**

        - id: class-service
          uri: lb://CLASS-SERVICE
          predicates:
            - Path=/classes/**,/teachersclasses/**
          filters:
            - AddRequestHeader=X-Gateway-Auth,valid

        - id: attendance-service
          uri: lb://ATTENDANCE-SERVICE
          predicates:
            - Path=/absences/**,/lessons/**
          filters:
            - AddRequestHeader=X-Gateway-Auth,valid

        - id: grade-service
          uri: lb://grade-service
          predicates:
            - Path=/grades/**
          filters:
            - AddRequestHeader=X-Gateway-Auth,valid

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
